### ISSUE TITLE
Sidebar for navigation

### ISSUE THREAD

**Issue by amanmibra** [GTHC/bluebull#23]
### Purpose
This will allow users to navigate through our multiple page routes that includes:

- Home
- Dashboard
- Calendar
- Settings
- Tenting 101
- FAQ

For this sprint, front end design is the only mandatory part, firebase integration will be an extra non-priority tasks that will roll over to next sprint.

**Comment by rikkikendall** [comment]
Sidebar Branch has a Functioning Sidebar implemented
