### ISSUE TITLE
Send follow-up email to Duke Basketball

### ISSUE THREAD

**Issue by vinitbytheminute** [GTHC/bluebull#8]
Hi Ms. Jones,

I am excited that Basketball season just started. My god our team looks phenomenal this year. As tenting season is approaching, I just wanted to set up an email with you, Ms. Savarino, and whomever else to talk about the state of the app and whether it addresses your recommendations made in the beginning of the semester. If possible, can we please meet before the November 15th regarding the application. 

Best,

**Comment by amanmibra** [comment]
Uh, can you do this in wiki instead. This is not what issues are meant for.

**Comment by amanmibra** [comment]
@vinitbytheminute
